---
apiVersion: ksm.services.openmcp.cloud/v1alpha1
kind: KubeStateMetricsConfig
metadata:
  name: test-config
  namespace: default
spec:
  customResourceStateConfig: |
    kind: CustomResourceStateMetrics
    spec:
      resources:
        - groupVersionKind:
            group: apps
            version: "v1"
            kind: "Deployment"
          labelsFromPath:
            name: [metadata, name]
            namespace: [metadata, namespace]
          metricNamePrefix: deployment
          metrics:
            - name: replicas_desired
              help: "Number of desired replicas for deployment"
              each:
                type: Gauge
                gauge:
                  path: [spec, replicas]
            - name: replicas_available
              help: "Number of available replicas for deployment"
              each:
                type: Gauge
                gauge:
                  path: [status, availableReplicas]
  targetNamespace: observability
